sudo: required
services:
  - docker
language: node_js
os: linux
cache: yarn
node_js:
  - stable
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
before_script:
  - npm run test:setup
script:
  - npm test
after_success:
  - npm run test:export-coverage && npx codecov
